import type { Asset } from '../types';

export const mockWatchlistAssets: Asset[] = [
  {
    id: 'petr4',
    symbol: 'PETR4',
    name: 'Petrobras PN',
    type: 'brazilian_stock',
    exchange: 'B3',
    marketSymbol: 'PETR4',
    quote: {
      price: 38.42,
      change: 0.81,
      changePercent: 2.15,
      currency: 'BRL',
      updatedAt: new Date().toISOString(),
    },
  },
  {
    id: 'vale3',
    symbol: 'VALE3',
    name: 'Vale ON',
    type: 'brazilian_stock',
    exchange: 'B3',
    marketSymbol: 'VALE3',
    quote: {
      price: 56.18,
      change: -0.34,
      changePercent: -0.6,
      currency: 'BRL',
      updatedAt: new Date().toISOString(),
    },
  },
  {
    id: 'crypto:BTC',
    marketSymbol: 'BTC',
    symbol: 'BTC',
    name: 'Bitcoin',
    type: 'crypto',
    exchange: 'Alpha Vantage',
    quote: {
      price: 108250.42,
      change: -956.18,
      changePercent: -0.88,
      currency: 'USD',
      updatedAt: new Date().toISOString(),
      marketCap: 2140000000000,
      volume: 42800000000,
    },
  },
  {
    id: 'crypto:ETH',
    marketSymbol: 'ETH',
    symbol: 'ETH',
    name: 'Ethereum',
    type: 'crypto',
    exchange: 'Alpha Vantage',
    quote: {
      price: 3248.93,
      change: 38.12,
      changePercent: 1.19,
      currency: 'USD',
      updatedAt: new Date().toISOString(),
      marketCap: 391000000000,
      volume: 18300000000,
    },
  },
];
